apiVersion: v1
kind: Pod
metadata:
  name: kuard
  labels:
    name: kuard
spec:
  containers:
    - name: kuard
      image: gcr.io/kuard-239816/kuard-amd64:1
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      livenessProbe:
        httpGet:
          path: /healthy
          port: 8080
        initialDelaySeconds: 5    # 5s delay before http request
        timeoutSeconds: 1         # 1s timeout
        periodSeconds: 10         # the probe is called each 10s
        failureThreshold: 3       # container restart if 3 probes failed
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
